# -- !Ups
ALTER TABLE "PlutoProjectType" ADD COLUMN K_DEFAULT_TEMPLATE INTEGER NULL ;
ALTER TABLE "PlutoProjectType" ADD CONSTRAINT FK_DEFAULT_TEMPLATE FOREIGN KEY (K_DEFAULT_TEMPLATE) REFERENCES "ProjectTemplate"(id);

# -- !Downs
ALTER TABLE "PlutoProjectType" DROP CONSTRAINT FK_DEFAULT_TEMPLATE;
ALTER TABLE "PlutoProjectType" DROP COLUMN K_DEFAULT_TEMPLATE;