# -- !Ups
ALTER TABLE "ProjectEntry" ADD COLUMN K_PROJECT_TEMPLATE_ID INTEGER NULL;
ALTER TABLE "ProjectEntry" ADD CONSTRAINT FK_PROJECT_TEMPLATE_ID FOREIGN KEY (K_PROJECT_TEMPLATE_ID) REFERENCES "ProjectTemplate"(id) DEFERRABLE INITIALLY DEFERRED;

# -- !Downs
ALTER TABLE "ProjectEntry" DROP CONSTRAINT FK_PROJECT_TEMPLATE_ID;
ALTER TABLE "ProjectEntry" DROP COLUMN "ProjectTemplateId";
