# --!Ups
ALTER TABLE "ProjectEntry" ADD COLUMN B_DELETABLE boolean null;
ALTER TABLE "ProjectEntry" ADD COLUMN B_DEEPARCHIVE boolean null;
ALTER TABLE "ProjectEntry" ADD COLUMN B_SENSITIVE boolean null;

# --!Downs
ALTER TABLE "ProjectEntry" DROP COLUMN B_DELETABLE;
ALTER TABLE "ProjectEntry" DROP COLUMN B_DEEPARCHIVE;
ALTER TABLE "ProjectEntry" DROP COLUMN B_SENSITIVE;
