# --!Ups
ALTER TABLE "PlutoCommission" ALTER COLUMN I_COLLECTION_ID DROP NOT NULL;
ALTER TABLE "PlutoCommission" ADD COLUMN S_NOTES CHARACTER VARYING NULL;
ALTER TABLE "PlutoCommission" ADD COLUMN T_SCHEDULED_COMPLETION TIMESTAMP NULL;
ALTER TABLE "PlutoCommission" ADD COLUMN B_STORAGE_RULE_SENSITIVE BOOLEAN NULL;
ALTER TABLE "PlutoCommission" ADD COLUMN B_STORAGE_RULE_DELETABLE BOOLEAN NULL;
ALTER TABLE "PlutoCommission" ADD COLUMN S_PRODUCTION_OFFICE CHARACTER(3) NULL;

# --!Downs
ALTER TABLE "PlutoCommission" ALTER COLUMN I_COLLECTION_ID SET NOT NULL;
ALTER TABLE "PlutoCommission" DROP COLUMN S_NOTES;
ALTER TABLE "PlutoCommission" DROP COLUMN T_SCHEDULED_COMPLETION;
ALTER TABLE "PlutoCommission" DROP COLUMN B_STORAGE_RULE_SENSITIVE;
ALTER TABLE "PlutoCommission" DROP COLUMN B_STORAGE_RULE_DELETABLE;
ALTER TABLE "PlutoCommission" DROP COLUMN S_PRODUCTION_OFFICE;