# --!Ups
ALTER TABLE "FileEntry" ADD COLUMN K_MIRROR_PARENT BIGINT NULL;
ALTER TABLE "FileEntry" ADD COLUMN T_LOST_TIME TIMESTAMP NULL;
ALTER TABLE "FileEntry" ADD CONSTRAINT FK_MIRROR_PARENT FOREIGN KEY (K_MIRROR_PARENT) REFERENCES "FileEntry"(id) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE "StorageMirrorRow" (K_MIRROR_TARGET_ID BIGINT PRIMARY KEY,K_MIRROR_SOURCE_STORAGE_ID BIGINT NOT NULL);
ALTER TABLE "StorageMirrorRow" ADD CONSTRAINT FK_MIRROR_TARGET_ID FOREIGN KEY (K_MIRROR_TARGET_ID) REFERENCES "StorageEntry"(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "StorageMirrorRow" ADD CONSTRAINT FK_MIRROR_SOURCE_STORAGE FOREIGN KEY (K_MIRROR_SOURCE_STORAGE_ID) references "StorageEntry"(id) DEFERRABLE INITIALLY DEFERRED;

# --!Downs
ALTER TABLE "FileEntry" DROP CONSTRAINT FK_MIRROR_PARENT;
ALTER TABLE "FileEntry" DROP COLUMN K_MIRROR_PARENT;
ALTER TABLE "FileEntry" DROP COLUMN T_LOST_TIME;

DROP TABLE "StorageMirrorRow";