# -- !Ups
CREATE TABLE DEFAULTS (
  id INTEGER PRIMARY KEY NOT NULL,
  s_name CHARACTER VARYING UNIQUE NOT NULL,
  s_value CHARACTER VARYING NOT NULL
);


CREATE SEQUENCE "Defaults_id_seq"
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1;
ALTER SEQUENCE "Defaults_id_seq" OWNED BY DEFAULTS.id;

ALTER TABLE public.DEFAULTS OWNER TO projectlocker;
ALTER TABLE "Defaults_id_seq" OWNER TO projectlocker;

ALTER TABLE ONLY DEFAULTS ALTER COLUMN id SET DEFAULT nextval('"Defaults_id_seq"'::regclass);

# -- !Downs
DROP TABLE DEFAULTS;