# -- !Ups
ALTER TABLE "ProjectEntry" ADD COLUMN S_ADOBE_UUID CHARACTER VARYING NULL;
ALTER TABLE "ProjectType" ADD COLUMN S_PLUTO_TYPE CHARACTER VARYING NULL;
ALTER TABLE "ProjectType" ADD COLUMN S_PLUTO_SUBTYPE CHARACTER VARYING NULL;
ALTER TABLE "ProjectType" ADD CONSTRAINT C_UNIQUE_PLUTOID UNIQUE (S_PLUTO_TYPE, S_PLUTO_SUBTYPE);

# -- !Downs
ALTER TABLE "ProjectType" DROP CONSTRAINT C_UNIQUE_PLUTOID;
ALTER TABLE "ProjectEntry" DROP COLUMN S_ADOBE_UUID;
ALTER TABLE "ProjectType" DROP COLUMN S_PLUTO_TYPE;
ALTER TABLE "ProjectType" DROP COLUMN S_PLUTO_SUBTYPE