# -- !Ups
-- see https://stackoverflow.com/questions/8289100/create-unique-constraint-with-null-columns
CREATE UNIQUE INDEX C_STORAGE_UNIQUEPATHS_NOHOST ON "StorageEntry" (S_ROOT_PATH, S_STORAGE_TYPE) WHERE S_HOST IS NULL;
CREATE UNIQUE INDEX C_STORAGE_UNIQUEPATHS_WITHHOST ON "StorageEntry" (S_ROOT_PATH, S_STORAGE_TYPE, S_HOST) WHERE S_HOST IS NOT NULL;


# -- !Downs
DROP INDEX C_STORAGE_UNIQUEPATHS_WITHHOST;
DROP INDEX C_STORAGE_UNIQUEPATHS_NOHOST;